config/routes.rb
Rails.application.routes.draw do
  resources :audit_log_entries
  resources :employees
  resources :art_pieces
  resources :artists
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "art_pieces#index"

  resources :art_pieces
  resources :artists
  resources :audit_log_entries
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :first_name, :last_name, presence: true

  default_scope { order(last_name: :asc) }

  def full_name
    [last_name, first_name].join(", ")
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    add_breadcrumb("Inventory Browser", art_pieces_path)
    add_breadcrumb("Art Piece Entry", new_art_piece_path)
    add_breadcrumb("Artist Entry", new_artist_path)
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html {
          redirect_to new_art_piece_path, notice: "Artist was successfully created."
        }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :bio)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
  <p>
    <strong>First name:</strong>
    <%= artist.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= artist.last_name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= artist.bio %>
  </p>

</div>

app/views/artists/_form.html.erb
<div class="w-50">
  <%= form_with(model: artist) do |form| %>
    <% if artist.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

        <ul>
          <% artist.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex flex-row justify-content-between mb-3">
      <div class="flex-grow-1 pe-2">
        <%= form.label :first_name, style: "display: block" %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div class="flex-grow-1 ps-2">
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :bio, style: "display: block" %>
      <%= form.text_area :bio, class: "form-control" %>
    </div>

    <div class="mb-3 d-flex justify-content-between">
      <%= button_tag "Cancel", onclick: "window.history.back()", class: "btn btn-secondary" %>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <%= render artist %>
    <p>
      <%= link_to "Show this artist", artist %>
    </p>
  <% end %>
</div>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<%= render partial: "shared/header_and_tagline",
  locals: {
    title: "New Artist Entry",
    tagline: "Use the form below to add an artist to the system."
  }
%>

<%= render partial: "shared/breadcrumbs" %>

<div class="d-flex justify-content-center">
  <%= render "form", artist: @artist %>
</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete %>
</div>