config/routes.rb
Rails.application.routes.draw do
  resources :audit_log_entries
  resources :employees
  resources :art_pieces
  resources :artists
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "art_pieces#index"

  resources :art_pieces
  resources :artists
  resources :audit_log_entries
end

app/controllers/audit_log_entries_controller.rb
class AuditLogEntriesController < ApplicationController
  before_action :set_audit_log_entry, only: %i[ show ]

  # GET /audit_log_entries or /audit_log_entries.json
  def index
    @audit_log_entries = AuditLog.all
  end

  # GET /audit_log_entries/1 or /audit_log_entries/1.json
  def show
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_audit_log_entry
      @audit_log_entry = AuditLog.find(params[:id])
    end
end

app/helpers/audit_log_entries_helper.rb
module AuditLogEntriesHelper
end

app/views/audit_log_entries/_audit_log_entry.html.erb
<div>
  <p>
    <strong>Action:</strong>
    <%= audit_log_entry.action %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= audit_log_entry.employee_id %>
  </p>

  <p>
    <strong>Record:</strong>
    <%= audit_log_entry.record_id %>
  </p>

  <p>
    <strong>Before state:</strong>
    <pre><%= audit_log_entry.before_state %></pre>
  </p>

  <p>
    <strong>After state:</strong>
    <pre><%= audit_log_entry.after_state %></pre>
  </p>

</div>

app/views/audit_log_entries/_form.html.erb
<%= form_with(model: audit_log_entry) do |form| %>
  <% if audit_log_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(audit_log_entry.errors.count, "error") %> prohibited this audit_log_entry from being saved:</h2>

      <ul>
        <% audit_log_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :action, style: "display: block" %>
    <%= form.text_field :action %>
  </div>

  <div>
    <%= form.label :employee_id, style: "display: block" %>
    <%= form.text_field :employee_id %>
  </div>

  <div>
    <%= form.label :record_id, style: "display: block" %>
    <%= form.text_field :record_id %>
  </div>

  <div>
    <%= form.label :before_state, style: "display: block" %>
    <%= form.text_area :before_state %>
  </div>

  <div>
    <%= form.label :after_state, style: "display: block" %>
    <%= form.text_area :after_state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/audit_log_entries/edit.html.erb
<h1>Editing audit log entry</h1>

<%= render "form", audit_log_entry: @audit_log_entry %>

<br>

<div>
  <%= link_to "Show this audit log entry", @audit_log_entry %> |
  <%= link_to "Back to audit log entries", audit_log_entries_path %>
</div>

app/views/audit_log_entries/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: "shared/header_and_tagline",
  locals: {
    title: "Audit Log Entries",
    tagline: "View the list of audit records below to see who did what, and when."
  }
%>

<div id="audit_log_entries">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th>Employee</th>
        <th>Action</th>
        <th>URL</th>
        <th>Timestamp</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      <% @audit_log_entries.each do |audit_log_entry| %>
        <tr>
          <td><%= audit_log_entry.employee.full_name %></td>
          <td><%= audit_log_entry.action %></td>
          <td><%= link_to audit_log_entry.record.title, audit_log_entry.record.path %></td>
          <td><%= audit_log_entry.created_at %></td>
          <td><%= link_to "View Details", audit_log_entry_path(audit_log_entry.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/audit_log_entries/new.html.erb
<h1>New audit log entry</h1>

<%= render "form", audit_log_entry: @audit_log_entry %>

<br>

<div>
  <%= link_to "Back to audit log entries", audit_log_entries_path %>
</div>

app/views/audit_log_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: "audit_log_entries/audit_log_entry", locals: { audit_log_entry: @audit_log_entry } %>

<div>
  <%= link_to "Edit this audit log entry", edit_audit_log_entry_path(@audit_log_entry) %> |
  <%= link_to "Back to audit log entries", audit_log_entries_path %>

  <%= button_to "Destroy this audit log entry", audit_log_entry_path(@audit_log_entry), method: :delete %>
</div>