config/routes.rb
Rails.application.routes.draw do
  resources :audit_log_entries
  resources :employees
  resources :art_pieces
  resources :artists
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "art_pieces#index"

  resources :art_pieces
  resources :artists
  resources :audit_log_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :breadcrumbs

  def breadcrumbs
    @breadcrumbs ||= []
  end

  def add_breadcrumb(name, path = nil)
    breadcrumbs << Breadcrumb.new(name, path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class?(path)
    if request.path == path
      'active'
    else
      ''
    end
  end
end

app/views/application/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-primary border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Art Gallery IM
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inventory", art_pieces_path, class: "nav-link #{active_class?(art_pieces_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Employees", employees_path, class: "nav-link #{active_class?(employees_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Audit Log", audit_log_entries_path, class: "nav-link #{active_class?(audit_log_entries_path)}" %>
        </li>
      </ul>
      <span class="navbar-text">
      </span>
    </div>
  </div>
</nav>